# Base on https://github.com/pallets/click/blob/main/.github/workflows/tests.yaml
name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.12', os: ubuntu-latest, tox: py312}
          - {name: Windows, python: '3.12', os: windows-latest, tox: py312}
          - {name: Mac, python: '3.12', os: macos-latest, tox: py312}
          - {name: '3.11', python: '3.11', os: ubuntu-latest, tox: py311}
          - {name: '3.10', python: '3.10', os: ubuntu-latest, tox: py310}
          - {name: Typing, python: '3.12', os: ubuntu-latest, tox: typing}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: update pip
        run: |
          python -m pip install -U pip setuptools build
      - name: cache mypy
        uses: actions/cache@v4
        with:
          path: ./.mypy_cache
          key: mypy|${{ matrix.python }}|${{ hashFiles('pyproject.toml') }}
        if: matrix.tox == 'typing'
      - run: pip install tox
      - run: tox run -e ${{ matrix.tox }}
